name: Greet Everyone

on:
  # Triggers the workflow on push for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo 'Hello World!'
        id: hello
        
      - name: Show time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
